float2 in pos;
float4 in color_top;
float4 in color_bottom;
float2 uniform rect_dim;

unsigned int in gl_VertexIndex : INDEX;
// unsigned int in gl_InstanceID : INSTANCE;
float4 out gl_Position : POSITION;
float4 out color : COLOR0;

void main() {
    float is_top = (gl_VertexIndex & 2) >> 1;
    float2 corner = float2(gl_VertexIndex & 1, is_top);
    gl_Position = float4((corner * rect_dim) + pos, 0.0, 1.0);
    color = lerp(color_bottom, color_top, is_top);
}
